Updating with generic read/write functions

diff --git a/cxs_software/configure b/cxs_software/configure
--- a/cxs_software/configure
+++ b/cxs_software/configure
@@ -660,6 +660,9 @@ with_z_lib
 with_df_lib
 with_sz_lib
 with_jpeg_lib
+enable_idl_lib
+with_idl_inc
+with_idl_lib
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1277,6 +1280,13 @@ if test -n "$ac_init_help"; then
    esac
   cat <<\_ACEOF
 
+Optional Features:
+  --disable-option-checking  ignore unrecognized --enable/--with options
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+ --enable-idl_lib
+			build IDL wrappers for the cxs software library
+
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
@@ -1300,6 +1310,10 @@ Optional Packages:
 		  specify the directory where the sz libraries can be found
   --with-jpeg_lib
 		  specify the directory where the jpeg libraries can be found
+  --with-idl_inc
+		  specify the directory where the file idl_export.h can be found
+  --with-idl_lib
+		  specify the directory where the idl library can be found
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1428,52 +1442,6 @@ fi
   as_fn_set_status $ac_retval
 
 } # ac_fn_cxx_try_compile
-
-# ac_fn_cxx_try_link LINENO
-# -------------------------
-# Try to link conftest.$ac_ext, and return whether this succeeded.
-ac_fn_cxx_try_link ()
-{
-  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
-  rm -f conftest.$ac_objext conftest$ac_exeext
-  if { { ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
-$as_echo "$ac_try_echo"; } >&5
-  (eval "$ac_link") 2>conftest.err
-  ac_status=$?
-  if test -s conftest.err; then
-    grep -v '^ *+' conftest.err >conftest.er1
-    cat conftest.er1 >&5
-    mv -f conftest.er1 conftest.err
-  fi
-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext && {
-	 test "$cross_compiling" = yes ||
-	 $as_test_x conftest$ac_exeext
-       }; then :
-  ac_retval=0
-else
-  $as_echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_retval=1
-fi
-  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
-  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
-  # interfere with the next link command; also delete a directory that is
-  # left behind by Apple's compiler.  We do this before executing the actions.
-  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
-  eval $as_lineno_stack; test "x$as_lineno_stack" = x && { as_lineno=; unset as_lineno;}
-  as_fn_set_status $ac_retval
-
-} # ac_fn_cxx_try_link
 
 # ac_fn_cxx_try_cpp LINENO
 # ------------------------
@@ -1677,6 +1645,52 @@ $as_echo "$ac_res" >&6; }
   eval $as_lineno_stack; test "x$as_lineno_stack" = x && { as_lineno=; unset as_lineno;}
 
 } # ac_fn_cxx_check_header_compile
+
+# ac_fn_cxx_try_link LINENO
+# -------------------------
+# Try to link conftest.$ac_ext, and return whether this succeeded.
+ac_fn_cxx_try_link ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  rm -f conftest.$ac_objext conftest$ac_exeext
+  if { { ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+$as_echo "$ac_try_echo"; } >&5
+  (eval "$ac_link") 2>conftest.err
+  ac_status=$?
+  if test -s conftest.err; then
+    grep -v '^ *+' conftest.err >conftest.er1
+    cat conftest.er1 >&5
+    mv -f conftest.er1 conftest.err
+  fi
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then :
+  ac_retval=0
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_retval=1
+fi
+  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
+  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
+  # interfere with the next link command; also delete a directory that is
+  # left behind by Apple's compiler.  We do this before executing the actions.
+  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
+  eval $as_lineno_stack; test "x$as_lineno_stack" = x && { as_lineno=; unset as_lineno;}
+  as_fn_set_status $ac_retval
+
+} # ac_fn_cxx_try_link
 
 # ac_fn_cxx_check_func LINENO FUNC VAR
 # ------------------------------------
@@ -2711,147 +2725,40 @@ fi
 
 #Check to see if the user wants the IDL wrappers compiled
 #and check that the idl_export.h header can be found
-#AC_ARG_ENABLE([idl_lib], [ --enable-idl_lib
-#			build IDL wrappers for the cxs software library ])
-#AC_ARG_WITH(idl-inc, [  --with-idl_inc
-#		  specify the directory where the file idl_export.h can be found])
+# Check whether --enable-idl_lib was given.
+if test "${enable_idl_lib+set}" = set; then :
+  enableval=$enable_idl_lib;
+fi
+
+
+# Check whether --with-idl-inc was given.
+if test "${with_idl_inc+set}" = set; then :
+  withval=$with_idl_inc;
+fi
+
+
+# Check whether --with-idl-lib was given.
+if test "${with_idl_lib+set}" = set; then :
+  withval=$with_idl_lib;
+fi
+
+
+
 
 #enable_idl_lib=yes
 
-#IDL_FLAG=
+IDL_FLAG=
 
-#if test "$enable_idl_lib" = "yes"
-#then
-IDL_FLAG="DO_IDL=TRUE"
-do_idl=$IDL_FLAG
-
-#	if test "$with_idl_inc" != ""
-#	then
-#		CXXFLAGS="-I$with_idl_inc $CXXFLAGS"
-#	fi
-#	AC_CHECK_HEADER([idl_export.h], [], [
-#	  echo "" &&
-#  	  echo "ERROR: Could not find the idl_export.h header." &&
-#  	  echo "       Please specify the location with: " &&
-#  	  echo "       './configure --with-idl_inc=<path_to_idl_export.h> " &&
-#  	  exit -1
-#	  ])
-#fi
-
-
-LD_LIBRARY_PATH="$PWD/lib $LD_LIBRARY_PATH"
-
-if test "$with_mfhdf_inc" != ""
+if test "$enable_idl_lib" = "yes"
 then
-	CXXFLAGS="-I$with_mfhdf_inc $CXXFLAGS"
-fi
+	IDL_FLAG="DO_IDL=TRUE"
+	do_idl=$IDL_FLAG
 
-if test "$with_mfhdf_lib" != ""
-then
-	LDFLAGS="-L$with_mfhdf_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_mfhdf_lib"
-fi
+	if test "$with_idl_inc" != ""
+	then
+		CXXFLAGS="-I$with_idl_inc $CXXFLAGS"
+	fi
 
-if test "$with_fftw_inc" != ""
-then
-	CXXFLAGS="-I$with_fftw_inc $CXXFLAGS"
-fi
-
-if test "$with_fftw_lib" != ""
-then
-	LDFLAGS="-L$with_fftw_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_fftw_lib"
-fi
-
-if test "$with_tiff_inc" != ""
-then
-	CXXFLAGS="-I$with_tiff_inc $CXXFLAGS"
-fi
-
-if test "$with_tiff_lib" != ""
-then
-	LDFLAGS="-L$with_tiff_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_tiff_lib"
-fi
-
-
-if test "$with_z_lib" != ""
-then
-	LDFLAGS="-L$with_z_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_z_lib"
-fi
-
-if test "$with_sz_lib" != ""
-then
-	LDFLAGS="-L$with_sz_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_sz_lib"
-fi
-
-if test "$with_df_lib" != ""
-then
-	LDFLAGS="-L$with_df_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_df_lib"
-fi
-
-if test "$with_jpeg_lib" != ""
-then
-	LDFLAGS="-L$with_jpeg_lib $LDFLAGS"
-	LD_RUN_PATH="$LD_RUN_PATH:$with_jpeg_lib"
-fi
-
-
-### Finished setting up the variables. Now check the libraries and headers.
-
-
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -lstdc++" >&5
-$as_echo_n "checking for main in -lstdc++... " >&6; }
-if test "${ac_cv_lib_stdcpp_main+set}" = set; then :
-  $as_echo_n "(cached) " >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lstdc++  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-return main ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_cxx_try_link "$LINENO"; then :
-  ac_cv_lib_stdcpp_main=yes
-else
-  ac_cv_lib_stdcpp_main=no
-fi
-rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_stdcpp_main" >&5
-$as_echo "$ac_cv_lib_stdcpp_main" >&6; }
-if test "x$ac_cv_lib_stdcpp_main" = x""yes; then :
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSTDC__ 1
-_ACEOF
-
-  LIBS="-lstdc++ $LIBS"
-
-else
-
-  echo "" &&
-  echo "ERROR: Could not find the stdc++ library." &&
-  echo "       Please fix before proceeding " &&
-  exit -1
-
-fi
-
-
-
-#Checks for fftw3
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3246,6 +3153,192 @@ fi
 done
 
 
+ac_fn_cxx_check_header_mongrel "$LINENO" "idl_export.h" "ac_cv_header_idl_export_h" "$ac_includes_default"
+if test "x$ac_cv_header_idl_export_h" = x""yes; then :
+
+else
+
+	  echo "" &&
+  	  echo "ERROR: Could not find the idl_export.h header." &&
+  	  echo "       Please specify the location with: " &&
+  	  echo "       './configure --with-idl_inc=<path_to_idl_export.h> " &&
+  	  exit -1
+
+fi
+
+
+	if test "$with_idl_lib" != ""
+	then
+		LDFLAGS="-L$with_idl_lib $LDFLAGS"
+		LD_RUN_PATH="$LD_RUN_PATH:$with_idl_lib"
+	fi
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for IDL_Message in -lidl" >&5
+$as_echo_n "checking for IDL_Message in -lidl... " >&6; }
+if test "${ac_cv_lib_idl_IDL_Message+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lidl  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char IDL_Message ();
+int
+main ()
+{
+return IDL_Message ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"; then :
+  ac_cv_lib_idl_IDL_Message=yes
+else
+  ac_cv_lib_idl_IDL_Message=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_idl_IDL_Message" >&5
+$as_echo "$ac_cv_lib_idl_IDL_Message" >&6; }
+if test "x$ac_cv_lib_idl_IDL_Message" = x""yes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBIDL 1
+_ACEOF
+
+  LIBS="-lidl $LIBS"
+
+else
+
+  	  echo "" &&
+  	  echo "ERROR: Could not find the idl library." &&
+  	  echo "       Please specify the location with: " &&
+  	  echo "       './configure --with-idl_lib=<path_to_idl_library> " &&
+  	  exit -1
+
+fi
+
+fi
+
+LD_LIBRARY_PATH="$PWD/lib $LD_LIBRARY_PATH"
+
+if test "$with_mfhdf_inc" != ""
+then
+	CXXFLAGS="-I$with_mfhdf_inc $CXXFLAGS"
+fi
+
+if test "$with_mfhdf_lib" != ""
+then
+	LDFLAGS="-L$with_mfhdf_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_mfhdf_lib"
+fi
+
+if test "$with_fftw_inc" != ""
+then
+	CXXFLAGS="-I$with_fftw_inc $CXXFLAGS"
+fi
+
+if test "$with_fftw_lib" != ""
+then
+	LDFLAGS="-L$with_fftw_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_fftw_lib"
+fi
+
+if test "$with_tiff_inc" != ""
+then
+	CXXFLAGS="-I$with_tiff_inc $CXXFLAGS"
+fi
+
+if test "$with_tiff_lib" != ""
+then
+	LDFLAGS="-L$with_tiff_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_tiff_lib"
+fi
+
+
+if test "$with_z_lib" != ""
+then
+	LDFLAGS="-L$with_z_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_z_lib"
+fi
+
+if test "$with_sz_lib" != ""
+then
+	LDFLAGS="-L$with_sz_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_sz_lib"
+fi
+
+if test "$with_df_lib" != ""
+then
+	LDFLAGS="-L$with_df_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_df_lib"
+fi
+
+if test "$with_jpeg_lib" != ""
+then
+	LDFLAGS="-L$with_jpeg_lib $LDFLAGS"
+	LD_RUN_PATH="$LD_RUN_PATH:$with_jpeg_lib"
+fi
+
+
+### Finished setting up the variables. Now check the libraries and headers.
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -lstdc++" >&5
+$as_echo_n "checking for main in -lstdc++... " >&6; }
+if test "${ac_cv_lib_stdcpp_main+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lstdc++  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"; then :
+  ac_cv_lib_stdcpp_main=yes
+else
+  ac_cv_lib_stdcpp_main=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_stdcpp_main" >&5
+$as_echo "$ac_cv_lib_stdcpp_main" >&6; }
+if test "x$ac_cv_lib_stdcpp_main" = x""yes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSTDC__ 1
+_ACEOF
+
+  LIBS="-lstdc++ $LIBS"
+
+else
+
+  echo "" &&
+  echo "ERROR: Could not find the stdc++ library." &&
+  echo "       Please fix before proceeding " &&
+  exit -1
+
+fi
+
+
+
+#Checks for fftw3
 ac_fn_cxx_check_header_mongrel "$LINENO" "fftw3.h" "ac_cv_header_fftw3_h" "$ac_includes_default"
 if test "x$ac_cv_header_fftw3_h" = x""yes; then :
 
